### ISSUE TITLE
Add Welcome Valley to the game.

### ISSUE THREAD

**Issue by craigy109** [MikeTheToon/Toontown-Crystal#68]
This is almost done need to fix up the ai errors if anyone wants to help i would be happy.
https://github.com/MikeTheToon/Toontown-Crystal/tree/Welcome-Valley-Import

Error i currently get is
  File "src\toontown\ai\ToontownAIRepository.py", line 209, in handleConnected
    self.createSafeZones()
  File "src\toontown\ai\ToontownAIRepository.py", line 155, in createSafeZones
    self.hoods.append(TTHoodAI.TTHoodAI(self))
AttributeError: 'module' object has no attribute 'TTHoodAI'

**Comment by DenialMC** [comment]
well if you even try to do this you'll fail because I was the one who holocausted Welcome Valley entirely from the game.. so if you try to add it back, you'll end up breaking the whole game.. like when I did when I removed it :dancer:

**Comment by Virnios** [comment]
#rekt thx for stopping bye bby <3

**Comment by DenialMC** [comment]
no luck

**Comment by Virnios** [comment]
Not nice to delete someones comment.
